### ISSUE TITLE
Resizer gets selected and doesn't unselect

### ISSUE THREAD

**Issue by phillip-haydon** [fluentCODE/ScrawlIssues#23] opened 2015-03-09 06:02 UTC
![image](https://cloud.githubusercontent.com/assets/895629/6550523/e3e2ad34-c664-11e4-84c9-600ebb2bdab8.png)

**Comment by stirno** [comment] 2015-03-13 04:38
This is basically accessibility hints in action. As soon as you focus another control it will stop displaying that way. We had other issues with focus before that @pauljz has now fixed so I'm going to assume this is now behaving as intended for everyone (it is for us). Reopen if its still going crazy, preferably with a gif! Thanks!

**Closed as completed by stirno** 2015-03-13 04:38 UTC
